$bg0 = rgb(1e1e2e) # Base
$bg1 = rgb(313244) # Surface 0
$bg2 = rgb(45475a) # Surface 1
$bg3 = rgb(585b70) # Surface 2
$bg4 = rgb(6c7086) # Overlay 0

$fg = rgb(cdd6f4) # Text

$accent = rgb(cba6f7) # Mauve

$red = rgb(f38ba8)
$orange = rgb(fab387) # Peach
$yellow = rgb(f9e2af)
$green = rgb(a6e3a1)
$teal = rgb(94e2d5)
$blue = rgb(89b4fa)
$purple = rgb(cba6f7) # Mauve
$pink = rgb(f5c2e7)

$grey0 = rgb(7f849c) # Overlay 1
$grey1 = rgb(9399b2) # Overlay 2
$grey2 = rgb(a6adc8) # Subtext 0

$dark = rgb(181825) # Mantle
$darker = rgb(11111b) # Crust