##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    #Keeps Street Fighter 6 Focused
    name= keep-sf6-focused
    match:title= Street Fighter 6
    idle_inhibit = always
    render_unfocused = true
}

windowrule {
    #Keeps Balatro Focused
    name= keep-sf6-focused
    match:title= Balatro
    idle_inhibit = always
    render_unfocused = true
}

windowrule{
    #Maintains kitty update system window floating
    name = kitty-floating-update-system
    match:class = update_system_float
    float = true
    stay_focused = true
    center = true
    size = 60% 50%
}

##############################
############LAYERS############
##############################

layerrule {
    name = rofi
    match:namespace = rofi
    animation = popin 95%
}

layerrule {
    name = wlogout
    match:namespace = logout_dialog
    blur = on
    animation = fade
}
